baseURL = "http://brfgoteborgsvagen81.se/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Göteborgsvägen 81"
theme = "meghna-hugo"

# Menu
[menu]

    [[menu.nav]]
    name = "Nyheter"
    URL = "blog"
    weight = 1

    [[menu.nav]]
    name = "Information"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Styrelse"
    URL = "our-team"
    weight = 3

    [[menu.nav]]
    name = "Kontakta oss"
    URL = "contact-us"
    weight = 4

# Site params
[params]
home= "Hem"
logo = ""
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "BRF Göteborgsvägen 81"
author = "Christopher Vikner"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]
email = "brfgoteborgsvagen81@gmail.com"

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-ion-play"
    heading = "Göteborgsvägen 81"
    content= "Mitt på Göteborgsvägen hittar man de boende i BRF Göteborgsvägen 81. En liten, men sammanhållen, skara människor som befinner sig i olika faser i livet. Tillsammans försöker vi skapa en trevlig och positiv plats att bo och umgås på."

    btn = true
    btnText="Om oss"
    btnURL="#blog"

    # call to action
    [params.cta]
    enable = false
    title = "Great Design & Incredible Features"
    content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi nostrum."
    btnURL = "#"
    btnText = "Start a project with us"

    # footer
    [params.footer]
    copyrightURL = "http://codeandcrayons.se"
    copyright = "Christopher Vikner | Template by Themefisher"
